# Site settings
title: Your awesome title
email: dom@islovely.co
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
profiles:
  dribbble: "domhabersack"
  github: "dhabersack"
  mastodonsocial: "@domhabersack"
  twitter: "domhabersack"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /posts/:title/

defaults:
  - scope:
      path: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "work/**/*"
    values:
      sitemap: false
  - scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false

exclude:
  - assets/heroes/cropped
  - assets/heroes/originals
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
