email: dom@islovely.co
title: islovely
github: dhabersack
twitter: dhabersack

name: islovely.co
description: Posts from the portolio of Dom Habersack.
url: http://islovely.co/posts
author: Dom Habersack

baseurl: ''
exclude: [Capfile, config, Gemfile, Gemfile.lock, README.md]
gems:
  - jekyll-feed
  - jekyll-sitemap
host: '0.0.0.0'
safe: false
sass:
  style: :compressed
url: 'http://islovely.co'

markdown: redcarpet
permalink: /posts/:title/
collections:
  pages:
    output: true
    permalink: /:title/
defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
