# Site settings
name: islovely
title: Your awesome title
email: dom@islovely.co
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://islovely.co" # the base hostname & protocol for your site, e.g. http://example.com
profiles:
  dribbble: "domhabersack"
  github: "domhabersack"
  mastodonsocial: "@domhabersack"
  twitter: "domhabersack"

# Build settings
keep_files: [assets]
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

permalink: /posts/:title/

collections:
  courses:
    output: true
  newsletters:
    output: true
    permalink: /newsletter/archive/:title/
  projects:
    output: true

defaults:
  - scope:
      path: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
  - scope:
      path: ""
      type: "newsletters"
    values:
      layout: "newsletter"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "work/**/*"
    values:
      sitemap: false
  - scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
  - scope:
      path: "assets/rich-previews"
    values:
      type: "rich-preview"

exclude:
  - assets/heroes/cropped
  - assets/heroes/originals
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
