export { default as A } from './a'
export { default as Figure } from './figure'
export { default as H1 } from './h1'
export { default as H2 } from './h2'
export { default as Li } from './li'
export { default as P } from './p'
export { default as Strong } from './strong'
