import React from 'react'

import A from './a'
import Li from './li'
import Ul from './ul'

export default () => (
  <nav>
    <Ul
      className={`
        flex
        flex-wrap
        list-style-none
        margin-0
        padding-0
        width-full
      `}
    >
      <Li
        className={`
          font-size-16-short
          font-weight-500
          margin-bottom-0
          margin-right-xs
          xs:margin-right-s
        `}
      >
        <A
          className={`
            inline-block
            padding-vertical-xs
          `}
          href="/courses"
        >
          Courses
        </A>
      </Li>

      <Li
        className={`
          font-size-16-short
          font-weight-500
          margin-bottom-0
          margin-right-xs
          xs:margin-right-s
        `}
      >
        <A
          className={`
            inline-block
            padding-vertical-xs
          `}
          href="/posts"
        >
          Blog
        </A>
      </Li>

      <Li
        className={`
          font-size-16-short
          font-weight-500
          margin-bottom-0
          margin-right-xs
          xs:margin-right-s
        `}
      >
        <A
          className={`
            inline-block
            padding-vertical-xs
          `}
          href="/firetips"
        >
          Fire tips
        </A>
      </Li>

      <Li
        className={`
          font-size-16-short
          font-weight-500
          margin-bottom-0
          margin-right-xs
          xs:margin-right-s
        `}
      >
        <A
          className={`
            inline-block
            padding-vertical-xs
          `}
          href="/newsletter"
        >
          Newsletter
        </A>
      </Li>

      <Li
        className={`
          font-size-16-short
          font-weight-500
          margin-bottom-0
          margin-right-xs
          xs:margin-right-s
        `}
      >
        <A
          className={`
            inline-block
            padding-vertical-xs
          `}
          href="/about"
        >
          About
        </A>
      </Li>

      <Li
        className={`
          font-size-16-short
          font-weight-500
          margin-bottom-0
        `}
      >
        <A
          className={`
            inline-block
            margin-bottom-0
            padding-vertical-xs
          `}
          href="/contact"
        >
          Contact
        </A>
      </Li>
    </Ul>
  </nav>
)
