import React from 'react'

import A from './a'
import Li from './li'
import Ul from './ul'

export default () => (
  <nav>
    <Ul
      className={`
        flex
        flex-wrap
        list-none
        m-0
        p-0
        w-full
      `}
    >
      <Li
        className={`
          font-size-16-short
          font-weight-500
          mb-0
          mr-10
          xs:mr-15
        `}
      >
        <A
          className={`
            inline-block
            py-6
          `}
          href="/courses/"
        >
          Courses
        </A>
      </Li>

      <Li
        className={`
          font-size-16-short
          font-weight-500
          mb-0
          mr-10
          xs:mr-15
        `}
      >
        <A
          className={`
            inline-block
            py-6
          `}
          href="/posts/"
        >
          Blog
        </A>
      </Li>

      <Li
        className={`
          font-size-16-short
          font-weight-500
          mb-0
          mr-10
          xs:mr-15
        `}
      >
        <A
          className={`
            inline-block
            py-6
          `}
          href="/firetips/"
        >
          Fire tips
        </A>
      </Li>

      <Li
        className={`
          font-size-16-short
          font-weight-500
          mb-0
          mr-10
          xs:mr-15
        `}
      >
        <A
          className={`
            inline-block
            py-6
          `}
          href="/newsletter/"
        >
          Newsletter
        </A>
      </Li>

      <Li
        className={`
          font-size-16-short
          font-weight-500
          mb-0
          mr-10
          xs:mr-15
        `}
      >
        <A
          className={`
            inline-block
            py-6
          `}
          href="/about"
        >
          About
        </A>
      </Li>

      <Li
        className={`
          font-size-16-short
          font-weight-500
          mb-0
        `}
      >
        <A
          className={`
            inline-block
            mb-0
            py-6
          `}
          href="/contact/"
        >
          Contact
        </A>
      </Li>
    </Ul>
  </nav>
)
