import React from 'react'

export default () => (
  <nav>
    <ul
      className={`
        flex
        flex-wrap
        list-none
        m-0
        p-0
        w-full
      `}
    >
      <li
        className={`
          font-medium
          mb-0
          mr-2.5
          text-base
          sm:mr-4
        `}
      >
        <a
          className={`
            inline-block
            py-1.5
          `}
          href="/courses/"
        >
          Courses
        </a>
      </li>

      <li
        className={`
          font-medium
          mb-0
          mr-2.5
          text-base
          sm:mr-4
        `}
      >
        <a
          className={`
            inline-block
            py-1.5
          `}
          href="/posts/"
        >
          Blog
        </a>
      </li>

      <li
        className={`
          font-medium
          mb-0
          mr-2.5
          text-base
          sm:mr-4
        `}
      >
        <a
          className={`
            inline-block
            py-1.5
          `}
          href="/firetips/"
        >
          Fire tips
        </a>
      </li>

      <li
        className={`
          font-medium
          mb-0
          mr-2.5
          text-base
          sm:mr-4
        `}
      >
        <a
          className={`
            inline-block
            py-1.5
          `}
          href="/newsletter/"
        >
          Newsletter
        </a>
      </li>

      <li
        className={`
          font-medium
          mb-0
          mr-2.5
          text-base
          sm:mr-4
        `}
      >
        <a
          className={`
            inline-block
            py-1.5
          `}
          href="/about"
        >
          About
        </a>
      </li>

      <li
        className={`
          font-medium
          mb-0
          text-base
        `}
      >
        <a
          className={`
            inline-block
            mb-0
            py-1.5
          `}
          href="/contact/"
        >
          Contact
        </a>
      </li>
    </ul>
  </nav>
)
